# Generated by Django 3.0.6 on 2020-05-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomapp', '0003_auto_20200523_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parts',
            field=models.ManyToManyField(to='bomapp.Part'),
        ),
        migrations.DeleteModel(
            name='BOM',
        ),
    ]
